### ISSUE TITLE
启动server时ImportError: cannot import name AxisValuesQuerySet

### ISSUE THREAD

**Issue by testerclub** [kinegratii/django-echarts#14]
你好，我用的python2.7，在sample下执行python manage.py runserver 127.0.0.1:8000启动server时报导入模块AxisValuesQuerySet出错

C02Q6NMPFVH5:example jackey$ python manage.py runserver 127.0.0.1:8000
Unhandled exception in thread started by <function wrapper at 0x10391d0c8>
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Library/Python/2.7/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/Library/Python/2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Library/Python/2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/jackey/PycharmProjects/django-echarts-master/example/demo/models.py", line 7, in <module>
    from django_echarts.datasets.managers import AxisValuesQuerySet
ImportError: cannot import name AxisValuesQuerySet

**Comment by kinegratii** [comment]
请按照以下提示进行排查：

1 django_echarts v0.3版本（包括master分支）**仅支持** Python 3.5+和Django 1.11+ 。
2 请确认引用了正确的 django_echarts 库， `django_echarts.datasets.managers.AxisValuesQuerySet` 中间有经过一次重命名
