### ISSUE TITLE
example无法运行

### ISSUE THREAD

**Issue by sailf** [kinegratii/django-echarts#17]
提示  ：
ImportError: This loader does not know module django.contrib.messages.migrations

**Comment by kinegratii** [comment]
请提供更多的异常 trace 信息

**Comment by Jiahe-J** [comment]
Traceback (most recent call last):
  File "/Users/silenthz/.virtualenvs/commonEnv/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Users/silenthz/.virtualenvs/commonEnv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 127, in inner_run
    self.check_migrations()
  File "/Users/silenthz/.virtualenvs/commonEnv/lib/python3.6/site-packages/django/core/management/base.py", line 422, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/silenthz/.virtualenvs/commonEnv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/silenthz/.virtualenvs/commonEnv/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/Users/silenthz/.virtualenvs/commonEnv/lib/python3.6/site-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.load_disk()
  File "/Users/silenthz/.virtualenvs/commonEnv/lib/python3.6/site-packages/django/db/migrations/loader.py", line 82, in load_disk
    module = import_module(module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 946, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 885, in _find_spec
  File "/Users/silenthz/.virtualenvs/commonEnv/lib/python3.6/site-packages/macropy/core/import_hooks.py", line 134, in find_spec
    source = spec.loader.get_source(fullname)
  File "/Users/silenthz/.virtualenvs/commonEnv/lib/python3.6/site-packages/django/utils/six.py", line 222, in get_code
    self.__get_module(fullname)  # eventually raises ImportError
  File "/Users/silenthz/.virtualenvs/commonEnv/lib/python3.6/site-packages/django/utils/six.py", line 193, in __get_module
    raise ImportError("This loader does not know module " + fullname)
ImportError: This loader does not know module django.contrib.messages.migrations

requirements.txt也缺乏完整的依赖列表

**Comment by Jiahe-J** [comment]
pip install pyecharts==0.4.1 
将pyecharts回退到这个版本才可以用。

**Comment by kinegratii** [comment]
@Jiahe-J @sailf  目前暂不支持 pyecharts v0.5.0+

**Comment by Jiahe-J** [comment]
在requirements.txt里加一下吧，小白我废了挺大劲才发现的  o(╥﹏╥)o

**Comment by kinegratii** [comment]
See also #18
