### ISSUE TITLE
django.template.exceptions.TemplateDoesNotExist: snippets/echarts_init_options.tpl

### ISSUE THREAD

**Issue by gerayking** [kinegratii/django-echarts#33]
我想要使用该模块在我的毕设中展示数据，但是在quickstart的过程中出现了上述问题， 下面是我的版本详情以及代码
python 3.1
django-echarts 0.5.1
django 3.1.4

urls.py
```py
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(site_obj.urls))
]
```
site_views.py
```py
# ...
from django_echarts.starter.sites import DJESite
from django_echarts.entities import Copyright
from pyecharts import options as opts
from pyecharts.charts import Bar

site_obj = DJESite(site_title='福建统计')

site_obj.add_widgets(copyright_=Copyright(start_year=2022, powered_by='Zinc'))

chart_description = '截止2020年底，福建省土地面积1240.29万公顷，占我国国土总面积1.3%。全省森林面积811.58万公顷，森林覆盖率为66.8%，连续42年位居全国首位。'


@site_obj.register_chart(title='森林覆盖率', description=chart_description, catalog='基本信息')
def fujian_forest_coverage():
    bar = Bar().add_xaxis(
        ['福州', '厦门', '莆田', '三明', '漳州', '泉州', '南平', '龙岩', '宁德']
    ).add_yaxis(
        '森林覆盖率', [54.7, 45, 58.1, 76.8, 63.4, 61, 75.3, 78, 75]
    ).set_global_opts(
        title_opts=opts.TitleOpts(title="福建省各地市森林覆盖率", subtitle="单位：%"),
        visualmap_opts=opts.VisualMapOpts(is_show=True, max_=100, min_=0)).set_series_opts(
        markline_opts=opts.MarkLineOpts(
            data=[
                opts.MarkLineItem(y=66.8, name="全省"),
            ]
        )
    )
    return bar
```
settings.py
```py
"""
Django settings for economic project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '384$nu%q&rr9czc_iuy1k-(3q33qz0af97y1ktc6g&jcnu6&^v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_echarts',
    'django_echarts.contrib.bootstrap5',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'economic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'economic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

```

报错信息
```shell
[01/May/2022 17:49:09] "GET /chart/fujian_forest_coverage/ HTTP/1.1" 500 188347
Internal Server Error: /chart/fujian_forest_coverage/
Traceback (most recent call last):
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\home\geray\env\python3.7\lib\site-packages\django_echarts\templatetags\echarts.py", line 60, in echarts_js_content
    contents = build_echarts_initial_fragment(*echarts)
  File "C:\home\geray\env\python3.7\lib\site-packages\django_echarts\templatetags\echarts.py", line 55, in build_echarts_initial_fragment
    return SafeString(render_to_string('snippets/echarts_init_options.tpl', context))
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\home\geray\env\python3.7\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: snippets/echarts_init_options.tpl
```

**Comment by gerayking** [comment]
貌似安装django-echarts时出了问题， 卸载重新安装即可
